version: '3'

networks:
  default:
    ipam:
      config:
      - subnet: ${NETWORK_SUBNET}

services:
  influxdb:
    build:
      context: ./images/influxdb/
      dockerfile: ./${TYPE}/Dockerfile
      args:
        INFLUXDB_TAG: ${INFLUXDB_TAG}
    image: "influxdb"
    volumes:
      - ../.data/influxdb/data:/var/lib/influxdb
      - ./influxdb/config/:/etc/influxdb/
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089"
    networks:
      default:
        aliases:
        - influx

  chronograf:
    build:
      context: ./images/chronograf
      dockerfile: ./${TYPE}/Dockerfile
      args:
        CHRONOGRAF_TAG: ${CHRONOGRAF_TAG}
    image: "chrono_config"
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      - ../.data/chronograf/data/:/var/lib/chronograf/
    links:
      - influxdb
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb
    networks:
      default:
        aliases:
        - chronograf

  documentation:
    build:
      context: ./documentation
    ports:
      - "3010:3000"
